version: '3'
services:
  frontend-app:
    container_name: mercado-libre-app
    image: alver23/mercado-libre
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    environment:
      - NODE_ENV=3000
    ports:
      - 80:3000
    restart: always
